### ISSUE TITLE
[Webapp] Upload CSV for User creation.

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/openchs-webapp#61]
CSV with the Column header
- username @ suffix (This suffix will be automatically added when CSV will be uploaded).
- Name of User
- Email address (Mandatory)
- Contact Number (10 Digit)(Mandatory)
- Administrator (YES/NO)
- Language (Hindi/Gujrati/English/Marathi)
- Track Location (YES/NO)

The CSV will be accepted only if uploaded in this format.

**Comment by hithacker** [comment]
closing this as it's merged in https://app.zenhub.com/workspaces/openchs-5cf8e458bf08585333fd64ac/issues/openchs/openchs-webapp/65.
