### ISSUE TITLE
[Platform] Introduce organisation short name in organisation table

### ISSUE THREAD

**Issue by hithacker** [OpenCHS/openchs-webapp#9]
Introduce organisation short name in organisation table. In webapp use this to append @{shortname} postfix to username.
https://docs.google.com/spreadsheets/d/1cVy2Lz1_A9f8RP3HhNUfvbCkrgMjA4k4nUy6Figx5NI/edit#gid=2134823698&range=D3

**Comment by sidsamanvay** [comment]
username_suffix is added to organisation column.
